services:
  - type: web
    name: dvig1
    env: node
    nodeVersion: 18.14.0
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
