services:
  - type: web
    name: motors-shop
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 